<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class InvitationMail extends Mailable
{
    use Queueable, SerializesModels;
    public $user_name;
    public $user_email;
    public $redirectLink;
    public $organisation_logo;
    public $sender;
    public $organisation_name;
    public $role;
    public $year;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($user_name, $user_email, $redirectLink, $organisation_logo, $sender, $organisation_name, $role, $year)
    {
        $this->user_name = $user_name;
        $this->user_email = $user_email;
        $this->redirectLink = $redirectLink;
        $this->organisation_logo = $organisation_logo;
        $this->sender = $sender;
        $this->organisation_name = $organisation_name;
        $this->role = $role;
        $this->year = $year;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->markdown('mail.invitation-mail')->with([
            'user_name'     => $this->user_name,
            'user_email'    => $this->user_email,
            'redirectLink'  => $this->redirectLink,
            'organisation_logo' => $this->organisation_logo,
            'sender'            => $this->sender,
            'organisation_name' => $this->organisation_name,
            'role'              => $this->role,
            'year'              => $this->year
        ]);
    }

    public function subject($subject)
    {
        return "Member Invitation Mail"; // TODO: Change the autogenerated stub
    }


}
